# Generated by Django 3.2 on 2021-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Vulnerable Blog', max_length=255),
        ),
    ]
