# Generated by Django 3.2 on 2021-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnblogapp', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
