# Generated by Django 3.2 on 2021-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnblogapp', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog post...', max_length=255),
        ),
    ]
